// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzlzejyrsbkhfkxfxcwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6bHplanlyc2JraGZreGZ4Y3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxODg1NTgsImV4cCI6MjA2MTc2NDU1OH0.Iyo5sEJQfV1Yrr33Xn3-xR2kk7Tau_y7J3pTejhOQRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);